version: '3.2'


services:
    dev:
        image: klakegg/hugo:0.69.2-ext-asciidoctor
        ports:
            - "1313:1313"         
        volumes:
            - ".:/src:rw"
            - "./public:/target:rw"
        command: server

    prod:
        image: klakegg/hugo:0.69.2-ext-asciidoctor
        command: server
        volumes:
            - ".:/src"
        ports:
            - "1313:1313"        